Repository YAPP-Github/Bitnagil-Android, pull requests merged in 2025-08, with the labels that each got.

#71 [RELEASE/1.0]: 1.0 버전 배포 전 수정
  app/src/main/java/com/threegap/bitnagil/MainNavHost.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/SettingScreen.kt
Labels: 🧤 대현, 세환

#78 [Hotfix/#74] 온보딩 추천 루틴 삭제 시 오류 수정
  data/src/main/java/com/threegap/bitnagil/data/routine/model/request/RoutineByDayDeletionRequestDto.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/RoutineByDayDeletion.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/HomeScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/RoutineUiModel.kt
Labels: 🐞 Fix, 🧤 대현

#79 [Fix/#77] 로그인 관련 문제사항 수정
  app/src/main/java/com/threegap/bitnagil/MainNavHost.kt
  app/src/main/java/com/threegap/bitnagil/MainNavigator.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/mapper/AuthMapper.kt
  domain/src/main/java/com/threegap/bitnagil/domain/auth/model/UserRole.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/intro/IntroScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/LoginScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/LoginViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/model/LoginSideEffect.kt
Labels: 🐞 Fix, 🧤 대현

#84 [UI 배경 색상 설정 이후 statusBar 패딩이 적용되도록 수정
  presentation/src/main/java/com/threegap/bitnagil/presentation/emotion/EmotionScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/intro/IntroScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/LoginScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/onboarding/OnBoardingScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/SettingScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/terms/TermsAgreementScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/webview/BitnagilWebViewScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/WriteRoutineScreen.kt
Labels: 📱 UI, 세환

#92 [UI/#91] 디자인 시스템 변경 사항 반영
  app/src/main/java/com/threegap/bitnagil/navigation/home/HomeBottomNavigationBar.kt
  app/src/main/java/com/threegap/bitnagil/navigation/home/HomeNavHost.kt
  app/src/main/java/com/threegap/bitnagil/navigation/home/HomeRoute.kt
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_home_empty.xml
  app/src/main/res/drawable/ic_home_fill.xml
  app/src/main/res/drawable/ic_mypage_empty.xml
  app/src/main/res/drawable/ic_mypage_fill.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/ic_recommend_empty.xml
  app/src/main/res/drawable/ic_recommend_fill.xml
  app/src/main/res/drawable/ic_report_empty.xml
  app/src/main/res/drawable/ic_report_fill.xml
  app/src/main/res/drawable/ic_routine_recommend.xml
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/color/BitnagilColors.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/color/Color.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/component/atom/BitnagilFloatingButton.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/component/atom/BitnagilTextButton.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/component/block/BitnagilProgressTopBar.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/component/block/BitnagilTopBar.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/font/Font.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/typography/Type.kt
  core/designsystem/src/main/res/drawable/ic_add_routine.xml
  core/designsystem/src/main/res/drawable/ic_back_arrow_36.xml
  core/designsystem/src/main/res/drawable/ic_check_circle.xml
  core/designsystem/src/main/res/drawable/ic_check_default.xml
  core/designsystem/src/main/res/drawable/ic_check_lg.xml
  core/designsystem/src/main/res/drawable/ic_check_md.xml
  core/designsystem/src/main/res/drawable/ic_chevron_left_lg.xml
  core/designsystem/src/main/res/drawable/ic_chevron_left_md.xml
  core/designsystem/src/main/res/drawable/ic_chevron_right_md.xml
  core/designsystem/src/main/res/drawable/ic_logo.xml
  core/designsystem/src/main/res/drawable/ic_routine_add.xml
  core/designsystem/src/main/res/drawable/ic_routine_success.xml
  core/designsystem/src/main/res/font/cafe_24_ssurround_air_v1_1.otf
Labels: 📱 UI, 🧤 대현

#94 [Refactor/#93] BitnagilTextButton 공통 컴포넌트 수정
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/component/atom/BitnagilTextButton.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/emotion/EmotionScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/onboarding/component/template/OnBoardingSelectTemplate.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/WriteRoutineScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/template/TimePickerBottomSheet.kt
Labels: 🔨 Refactor, 📱 UI, 🧤 대현

#96 [UI/#95] 로그인, 약관동의 화면 리디자인 변경사항 반영
  app/src/main/java/com/threegap/bitnagil/MainNavHost.kt
  app/src/main/java/com/threegap/bitnagil/Route.kt
  core/designsystem/src/main/res/drawable-hdpi/intro_character.png
  core/designsystem/src/main/res/drawable-hdpi/login_fomo.png
  core/designsystem/src/main/res/drawable-mdpi/intro_character.png
  core/designsystem/src/main/res/drawable-mdpi/login_fomo.png
  core/designsystem/src/main/res/drawable-xhdpi/intro_character.png
  core/designsystem/src/main/res/drawable-xhdpi/login_fomo.png
  core/designsystem/src/main/res/drawable-xxhdpi/intro_character.png
  core/designsystem/src/main/res/drawable-xxhdpi/login_fomo.png
  core/designsystem/src/main/res/drawable-xxxhdpi/intro_character.png
  core/designsystem/src/main/res/drawable-xxxhdpi/login_fomo.png
  presentation/src/main/java/com/threegap/bitnagil/presentation/intro/IntroScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/intro/IntroViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/intro/model/IntroIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/intro/model/IntroSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/intro/model/IntroState.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/LoginScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/SettingScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/SettingViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/model/mvi/SettingSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/SplashScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/SplashViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/model/SplashIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/model/SplashSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/terms/TermsAgreementScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/terms/component/TermsAgreementItem.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/terms/component/ToggleAllAgreementsItem.kt
Labels: 📱 UI, 🧤 대현

#101 [Ui/#100] 마이페이지, 설정 화면 리디자인 변경 사항 반영
  app/src/main/java/com/threegap/bitnagil/navigation/home/HomeBottomNavigationBar.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/component/atom/BitnagilTextButton.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/component/block/BitnagilOptionButton.kt
  core/designsystem/src/main/res/drawable/ic_modal_warning.xml
  core/designsystem/src/main/res/drawable/ic_setting.xml
  presentation/src/main/java/com/threegap/bitnagil/presentation/mypage/MyPageScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/SettingScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/SettingViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/component/atom/settingtitle/SettingTitle.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/component/block/LogoutConfirmDialog.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/model/ConfirmDialogType.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/model/mvi/SettingIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/model/mvi/SettingState.kt
Labels: 📱 UI, 🧤 대현

#105 [UI/#103] 회원탈퇴 화면 UI를 구현합니다.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/threegap/bitnagil/MainNavHost.kt
  app/src/main/java/com/threegap/bitnagil/MainScreen.kt
  app/src/main/java/com/threegap/bitnagil/Route.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/component/atom/BitnagilSelectButton.kt
  core/designsystem/src/main/res/drawable/ic_check_circle_orange.xml
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/SettingScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/SettingViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/model/mvi/SettingIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/model/mvi/SettingSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/withdrawal/WithdrawalScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/withdrawal/WithdrawalViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/withdrawal/component/WithdrawalConfirmDialog.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/withdrawal/model/WithdrawalIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/withdrawal/model/WithdrawalReason.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/withdrawal/model/WithdrawalSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/withdrawal/model/WithdrawalState.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/WriteRoutineScreen.kt
Labels: 📱 UI, 🧤 대현

#115 [Feature/#114] 루틴 리스트 화면 미구현 기능을 구현합니다.
  app/src/main/java/com/threegap/bitnagil/MainActivity.kt
  app/src/main/java/com/threegap/bitnagil/MainNavigator.kt
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/component/atom/BitnagilToastMessage.kt
  core/designsystem/src/main/res/drawable/ic_warning.xml
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/DayOfWeek.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/common/toast/GlobalBitnagilToast.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/HomeScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/HomeViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/HomeSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/util/LocalDateExtension.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/routinelist/RoutineListScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/routinelist/RoutineListViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/routinelist/component/template/RoutineDetailsCard.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/routinelist/model/RoutineListIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/routinelist/model/RoutineListSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/routinelist/model/RoutineUiModel.kt
Labels: ✨ Feature, 🧤 대현

#121 [FIX/#120] 루틴 작성시 추천 루틴 타입 누락 추가
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/model/request/RegisterRoutineRequest.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/repositoryImpl/WriteRoutineRepositoryImpl.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/repository/WriteRoutineRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/usecase/RegisterRoutineUseCase.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/WriteRoutineViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/mvi/WriteRoutineIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/mvi/WriteRoutineState.kt
Labels: 🐞 Fix, 세환

#118 [Feature/#116] 앱 강제 업데이트 로직을 구현합니다.
  app/src/main/java/com/threegap/bitnagil/di/data/DataSourceModule.kt
  app/src/main/java/com/threegap/bitnagil/di/data/RepositoryModule.kt
  app/src/main/java/com/threegap/bitnagil/di/data/ServiceModule.kt
  build-logic/convention/src/main/java/com/threegap/bitnagil/convention/AndroidApplicationPlugin.kt
  build-logic/convention/src/main/java/com/threegap/bitnagil/convention/AndroidLibraryPlugin.kt
  build-logic/convention/src/main/java/com/threegap/bitnagil/convention/extension/AppVersion.kt
  data/src/main/java/com/threegap/bitnagil/data/version/datasource/VersionDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/version/datasourceImpl/VersionDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/version/model/response/VersionCheckResponseDto.kt
  data/src/main/java/com/threegap/bitnagil/data/version/repositoryImpl/VersionRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/version/service/VersionService.kt
  domain/src/main/java/com/threegap/bitnagil/domain/version/model/UpdateRequirement.kt
  domain/src/main/java/com/threegap/bitnagil/domain/version/repository/VersionRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/version/usecase/CheckUpdateRequirementUseCase.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/SplashScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/SplashViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/component/template/ForceUpdateDialog.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/model/SplashIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/model/SplashState.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/util/PlayStoreUtils.kt
Labels: ✨ Feature, 🧤 대현
