Repository YAPP-Github/Bitnagil-Android, pull requests merged in 2025-07, with the labels that each got.

#19 [Refactor/#17] DI 생성 책임을 app 모듈로 이관
  app/src/main/java/com/threegap/bitnagil/di/core/DataStoreModule.kt
  app/src/main/java/com/threegap/bitnagil/di/core/NetworkModule.kt
  app/src/main/java/com/threegap/bitnagil/di/core/Qualifier.kt
  app/src/main/java/com/threegap/bitnagil/di/core/SecurityModule.kt
  core/datastore/build.gradle.kts
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/auth/crypto/TokenCrypto.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/auth/model/AuthToken.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/auth/serializer/AuthTokenSerializer.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/auth/serializer/AuthTokenSerializerImpl.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/auth/storage/AuthTokenDataStore.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/auth/storage/AuthTokenDataStoreImpl.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/auth/storage/AuthTokenStorageFactory.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/di/DataStoreModule.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/serializer/TokenSerializer.kt
  core/datastore/src/test/java/com/threegap/bitnagil/datastore/auth/serializer/AuthTokenSerializerImplTest.kt
  core/datastore/src/test/java/com/threegap/bitnagil/datastore/auth/storage/AuthTokenDataStoreImplTest.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/threegap/bitnagil/network/auth/AuthInterceptor.kt
  core/network/src/main/java/com/threegap/bitnagil/network/auth/TokenAuthenticator.kt
  core/network/src/main/java/com/threegap/bitnagil/network/token/TokenProvider.kt
  core/security/build.gradle.kts
  core/security/src/main/java/com/threegap/bitnagil/security/crypto/SecureCrypto.kt
  core/security/src/main/java/com/threegap/bitnagil/security/keystore/AndroidKeyProvider.kt
Labels: 🔨 Refactor, 🧤 대현

#25 [Feature/#24] 스플래시 화면 구현
  app/src/main/java/com/threegap/bitnagil/MainNavHost.kt
  app/src/main/java/com/threegap/bitnagil/MainNavigator.kt
  app/src/main/java/com/threegap/bitnagil/Route.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/auth/storage/AuthTokenDataStore.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/auth/storage/AuthTokenDataStoreImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/datasource/AuthLocalDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/datasourceimpl/AuthLocalDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/repositoryimpl/AuthRepositoryImpl.kt
  domain/src/main/java/com/threegap/bitnagil/domain/auth/repository/AuthRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/auth/usecase/HasTokenUseCase.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/intro/IntroScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/SplashScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/SplashViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/model/SplashIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/model/SplashSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/splash/model/SplashState.kt
Labels: ✨ Feature, 🧤 대현

#29 [Feature/#28] 약관동의 화면 구현
  app/src/main/java/com/threegap/bitnagil/MainNavHost.kt
  app/src/main/java/com/threegap/bitnagil/Route.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/datasource/AuthRemoteDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/datasourceimpl/AuthRemoteDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/mapper/AuthMapper.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/model/request/TermsAgreementRequestDto.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/repositoryimpl/AuthRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/service/AuthService.kt
  domain/src/main/java/com/threegap/bitnagil/domain/auth/model/TermsAgreement.kt
  domain/src/main/java/com/threegap/bitnagil/domain/auth/repository/AuthRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/auth/usecase/SubmitTermsAgreementUseCase.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/LoginScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/LoginViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/model/LoginSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/terms/TermsAgreementScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/terms/TermsAgreementViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/terms/component/TermsAgreementItem.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/terms/model/TermsAgreementIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/terms/model/TermsAgreementSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/terms/model/TermsAgreementState.kt
Labels: ✨ Feature, 🧤 대현

#34 [Feature/#30] 추천 루틴 화면 구현
  core/designsystem/src/main/java/com/threegap/bitnagil/designsystem/color/BitnagilColors.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/RecommendRoutineScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/RecommendRoutineViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/component/atom/RecommendCategoryChip.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/component/block/EmotionRecommendRoutineButton.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/component/block/RecommendRoutineItem.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/component/template/RoutineDifficultyBottomSheet.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/model/RecommendRoutine.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/model/RecommendRoutineIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/model/RecommendRoutineSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/model/RecommendRoutineState.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/type/RecommendRoutineCategory.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/recommendroutine/type/RecommendRoutineDifficulty.kt
Labels: ✨ Feature, 🧤 대현

#38 [Feature/#33] 루틴 등록/수정 화면 구현
  app/src/main/java/com/threegap/bitnagil/di/data/DataSourceModule.kt
  app/src/main/java/com/threegap/bitnagil/di/data/RepositoryModule.kt
  app/src/main/java/com/threegap/bitnagil/di/data/ServiceModule.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/datasource/WriteRoutineDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/datasourceImpl/WriteRoutineDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/model/dto/RoutineDto.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/model/dto/SubRoutineDto.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/model/dto/SubRoutineInfosDiffDto.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/model/request/EditRoutineRequest.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/model/request/RegisterRoutineRequest.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/repositoryImpl/WriteRoutineRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/service/WriteRoutineService.kt
  domain/build.gradle.kts
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/model/Date.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/model/RepeatDay.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/model/Routine.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/model/SubRoutine.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/model/SubRoutineDiff.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/model/Time.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/repository/WriteRoutineRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/usecase/EditRoutineUseCase.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/usecase/GetChangedSubRoutinesUseCase.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/usecase/GetRoutineUseCase.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/usecase/RegisterRoutineUseCase.kt
  domain/src/test/java/com/threegap/bitnagil/domain/writeroutine/usecase/GetChangedSubRoutinesUseCaseTest.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/WriteRoutineScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/WriteRoutineViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/atom/namefield/NameField.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/atom/selectcell/SelectCell.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/atom/strokebutton/StrokeButton.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/atom/textbutton/Preview.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/atom/textbutton/TextButton.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/atom/tooltipbutton/TooltipButton.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/atom/tooltipbutton/model/TooltipDirection.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/atom/tooltipbutton/model/TooltipPositionProvider.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/block/labeledcheckbox/LabeledCheckBox.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/template/Preview.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/component/template/TimePickerBottomSheet.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/Day.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/RepeatType.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/SelectableDay.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/SubRoutine.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/Time.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/WriteRoutineType.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/mvi/WriteRoutineIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/mvi/WriteRoutineSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/mvi/WriteRoutineState.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/navarg/WriteRoutineScreenArg.kt
  presentation/src/main/res/layout/spinner_time_picker.xml
  presentation/src/main/res/values/styles.xml
Labels: ✨ Feature, 세환

#41 [Feature/#39] 마이페이지/설정 화면 구현
  presentation/src/main/java/com/threegap/bitnagil/presentation/mypage/MyPageScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/mypage/model/MyPageIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/mypage/model/MyPageSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/mypage/model/MyPageState.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/SettingScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/SettingViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/component/atom/settingtitle/SettingTitle.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/component/atom/toggleswitch/Preview.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/component/atom/toggleswitch/ToggleSwitch.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/component/block/settingrowbutton/SettingRowButton.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/model/mvi/SettingIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/model/mvi/SettingSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/setting/model/mvi/SettingState.kt
Labels: ✨ Feature, 세환

#44 [Feature/#43] 감정 구슬 화면 구현
  app/src/main/java/com/threegap/bitnagil/di/data/DataSourceModule.kt
  app/src/main/java/com/threegap/bitnagil/di/data/RepositoryModule.kt
  app/src/main/java/com/threegap/bitnagil/di/data/ServiceModule.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/datasource/EmotionDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/datasourceImpl/EmotionDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/model/dto/EmotionRecommendedRoutineDto.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/model/dto/EmotionRecommendedSubRoutineDto.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/model/request/RegisterEmotionRequest.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/model/response/GetEmotionsResponse.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/model/response/RegisterEmotionResponse.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/repositoryImpl/EmotionRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/service/EmotionService.kt
  domain/src/main/java/com/threegap/bitnagil/domain/emotion/model/Emotion.kt
  domain/src/main/java/com/threegap/bitnagil/domain/emotion/repository/EmotionRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/emotion/usecase/GetEmotionsUseCase.kt
  domain/src/main/java/com/threegap/bitnagil/domain/emotion/usecase/RegisterEmotionUseCase.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/emotion/EmotionScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/emotion/EmotionViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/emotion/model/Emotion.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/emotion/model/mvi/EmotionIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/emotion/model/mvi/EmotionSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/emotion/model/mvi/EmotionState.kt
Labels: ✨ Feature, 세환

#42 [Feature/#23] 홈 화면 구현
  app/src/main/java/com/threegap/bitnagil/MainNavHost.kt
  app/src/main/java/com/threegap/bitnagil/di/data/DataSourceModule.kt
  app/src/main/java/com/threegap/bitnagil/di/data/RepositoryModule.kt
  app/src/main/java/com/threegap/bitnagil/di/data/ServiceModule.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/datasource/RoutineRemoteDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/datasourceImpl/RoutineRemoteDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/mapper/RoutineMapper.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/model/request/RoutineCompletionInfoDto.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/model/request/RoutineCompletionRequestDto.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/model/response/RoutineDto.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/model/response/RoutinesResponseDto.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/model/response/SubRoutineDto.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/repositoryImpl/RoutineRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/service/RoutineService.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/DayOfWeek.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/Routine.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/RoutineCompletion.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/RoutineCompletionInfo.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/RoutineType.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/Routines.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/SubRoutine.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/repository/RoutineRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/usecase/DeleteRoutineUseCase.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/usecase/FetchWeeklyRoutinesUseCase.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/usecase/RoutineCompletionUseCase.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/HomeScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/HomeViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/atom/RoundTriangleShape.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/block/RoutineItem.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/block/SpeechBubbleTooltip.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/block/SubRoutinesItem.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/template/CollapsibleHomeHeader.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/template/DeleteConfirmDialog.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/template/RoutineDetailsBottomSheet.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/template/RoutineEmptyView.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/template/RoutineSection.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/template/RoutineSortBottomSheet.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/template/WeeklyDatePicker.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/HomeIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/HomeSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/HomeState.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/RoutineSortType.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/RoutineUiModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/RoutinesUiModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/SubRoutineUiModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/util/CollapsibleHeaderState.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/util/LocalDateExtension.kt
Labels: ✨ Feature, 🧤 대현

#55 [Feature/#52] 홈 화면 추가된 API 연동
  app/src/main/java/com/threegap/bitnagil/di/data/DataSourceModule.kt
  app/src/main/java/com/threegap/bitnagil/di/data/RepositoryModule.kt
  app/src/main/java/com/threegap/bitnagil/di/data/ServiceModule.kt
  core/network/src/main/java/com/threegap/bitnagil/network/model/AuthToken.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/datasource/EmotionDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/datasourceImpl/EmotionDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/model/response/MyEmotionResponseDto.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/repositoryImpl/EmotionRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/service/EmotionService.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/datasource/RoutineRemoteDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/datasourceImpl/RoutineRemoteDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/mapper/RoutineMapper.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/model/request/RoutineByDayDeletionRequestDto.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/model/request/SubRoutineDeletionInfoDto.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/model/response/RoutineDto.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/model/response/SubRoutineDto.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/repositoryImpl/RoutineRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/service/RoutineService.kt
  data/src/main/java/com/threegap/bitnagil/data/user/datasource/UserDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/user/datasourceImpl/UserDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/user/model/response/UserProfileResponseDto.kt
  data/src/main/java/com/threegap/bitnagil/data/user/repositoryImpl/UserRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/user/service/UserService.kt
  domain/src/main/java/com/threegap/bitnagil/domain/emotion/model/MyEmotion.kt
  domain/src/main/java/com/threegap/bitnagil/domain/emotion/repository/EmotionRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/emotion/usecase/GetMyEmotionUseCase.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/Routine.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/RoutineByDayDeletion.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/SubRoutine.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/model/SubRoutineDeletionInfo.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/repository/RoutineRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/usecase/DeleteRoutineByDayUseCase.kt
  domain/src/main/java/com/threegap/bitnagil/domain/user/model/UserProfile.kt
  domain/src/main/java/com/threegap/bitnagil/domain/user/repository/UserRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/user/usecase/FetchUserProfileUseCase.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/HomeScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/HomeViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/block/RoutineItem.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/block/SubRoutinesItem.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/template/CollapsibleHomeHeader.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/template/RoutineDetailsBottomSheet.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/component/template/RoutineSection.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/EmotionBallType.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/HomeIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/HomeState.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/RoutineUiModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/model/SubRoutineUiModel.kt
Labels: ✨ Feature, 🧤 대현

#57 [Feature/#49] 단일 루틴/단일 추천 루틴 API 연결 및 기존 API 호출부 점검
  app/src/main/java/com/threegap/bitnagil/MainNavHost.kt
  data/src/main/java/com/threegap/bitnagil/data/auth/datasourceimpl/AuthRemoteDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/datasource/EmotionDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/datasourceImpl/EmotionDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/model/dto/EmotionDto.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/model/dto/EmotionRecommendedRoutineDto.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/model/response/GetEmotionsResponse.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/repositoryImpl/EmotionRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/emotion/service/EmotionService.kt
  data/src/main/java/com/threegap/bitnagil/data/onboarding/datasourceImpl/OnBoardingDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/onboarding/model/dto/OnBoardingItemDto.kt
  data/src/main/java/com/threegap/bitnagil/data/onboarding/model/dto/OnBoardingRecommendRoutineDto.kt
  data/src/main/java/com/threegap/bitnagil/data/recommendroutine/datasource/RecommendRoutineDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/recommendroutine/datasourceImpl/RecommendRoutineDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/recommendroutine/repositoryImpl/RecommendRoutineRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/recommendroutine/service/RecommendRoutineService.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/datasource/RoutineRemoteDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/datasourceImpl/RoutineRemoteDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/mapper/RoutineMapper.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/repositoryImpl/RoutineRepositoryImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/routine/service/RoutineService.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/datasource/WriteRoutineDataSource.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/datasourceImpl/WriteRoutineDataSourceImpl.kt
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/repositoryImpl/WriteRoutineRepositoryImpl.kt
  domain/src/main/java/com/threegap/bitnagil/domain/recommendroutine/repository/RecommendRoutineRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/recommendroutine/usecase/GetRecommendRoutineUseCase.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/repository/RoutineRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/routine/usecase/GetRoutineUseCase.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/model/RepeatDay.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/model/Time.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/repository/WriteRoutineRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/usecase/GetRoutineUseCase.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/WriteRoutineViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/Day.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/SubRoutine.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/writeroutine/model/Time.kt
Labels: ✨ Feature, 🐞 Fix, 세환

#60 [Feature/#59] 마이페이지 유저 프로필 API 연동
  data/src/main/java/com/threegap/bitnagil/data/emotion/service/EmotionService.kt
  data/src/main/java/com/threegap/bitnagil/data/user/service/UserService.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/mypage/MyPageViewModel.kt
Labels: ✨ Feature, 🐞 Fix, 🧤 대현

#64 [Feature/#63] 루틴 등록/수정시 홈 화면 리프레시 기능 구현
  data/src/main/java/com/threegap/bitnagil/data/writeroutine/repositoryImpl/WriteRoutineRepositoryImpl.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/model/WriteRoutineEvent.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/repository/WriteRoutineRepository.kt
  domain/src/main/java/com/threegap/bitnagil/domain/writeroutine/usecase/GetWriteRoutineEventFlowUseCase.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/home/HomeViewModel.kt
Labels: ✨ Feature, 세환

#67 [Feature/#66] 릴리즈 환경 세팅
  .github/workflows/develop_branch.yml
  app/build.gradle.kts
Labels: ⚙ Init, 세환
