Repository YAPP-Github/Bitnagil-Android, pull requests merged in 2025-06, with the labels that each got.

#6 [Feature/#3] BaseViewModel 구현
  build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/threegap/bitnagil/presentation/common/mviviewmodel/MviIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/common/mviviewmodel/MviSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/common/mviviewmodel/MviState.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/common/mviviewmodel/MviViewModel.kt
  presentation/src/test/java/com/threegap/bitnagil/presentation/common/mviviewmodel/MviViewModelTest.kt
Labels: ✨ Feature, ⚙ Init, 세환

#10 [Feature/#9] AuthToken 암복호화 로직 구현
  app/build.gradle.kts
  core/security/.gitignore
  core/security/build.gradle.kts
  core/security/consumer-rules.pro
  core/security/proguard-rules.pro
  core/security/src/main/AndroidManifest.xml
  core/security/src/main/java/com/threegap/bitnagil/security/AndroidKeyProvider.kt
  core/security/src/main/java/com/threegap/bitnagil/security/Crypto.kt
  core/security/src/main/java/com/threegap/bitnagil/security/KeyProvider.kt
  core/security/src/test/java/com/threegap/bitnagil/security/CryptoTest.kt
  settings.gradle.kts
Labels: ✨ Feature, ⚙ Init, 🧤 대현

#14 [Feature/#5] 카카오 소셜 로그인 구현
  .github/workflows/develop_branch.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/threegap/bitnagil/BitnagilApplication.kt
  app/src/main/java/com/threegap/bitnagil/MainNavHost.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/LoginScreen.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/LoginViewModel.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/model/LoginIntent.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/model/LoginSideEffect.kt
  presentation/src/main/java/com/threegap/bitnagil/presentation/login/model/LoginState.kt
  settings.gradle.kts
Labels: ✨ Feature, 🧤 대현

#15 [Feature/#8] AuthToken 저장을 위한 DataStore 구현
  core/datastore/build.gradle.kts
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/.gitkeep
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/di/DataStoreModule.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/model/AuthToken.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/serializer/AuthTokenSerializer.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/serializer/TokenSerializer.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/storage/AuthTokenDataStore.kt
  core/datastore/src/main/java/com/threegap/bitnagil/datastore/storage/AuthTokenDataStoreImpl.kt
  core/datastore/src/test/java/com/threegap/bitnagil/datastore/serializer/AuthTokenSerializerTest.kt
  core/datastore/src/test/java/com/threegap/bitnagil/datastore/storage/AuthTokenDataStoreImplTest.kt
  core/security/build.gradle.kts
  core/security/src/main/java/com/threegap/bitnagil/security/crypto/Crypto.kt
  core/security/src/main/java/com/threegap/bitnagil/security/crypto/SecureCrypto.kt
  core/security/src/main/java/com/threegap/bitnagil/security/di/SecurityModule.kt
  core/security/src/main/java/com/threegap/bitnagil/security/keystore/AndroidKeyProvider.kt
  core/security/src/main/java/com/threegap/bitnagil/security/keystore/KeyProvider.kt
  core/security/src/test/java/com/threegap/bitnagil/security/crypto/SecureCryptoTest.kt
  gradle/libs.versions.toml
Labels: ✨ Feature, 🧤 대현
